config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'gallery' => 'pages#gallery'
  get 'explore' => 'pages#explore'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def gallery
  end

  def explore
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	 <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <title>Tokuriki App 徳力アップ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= yield %>

</body>
</html>

app/views/pages/_gallery1.html.erb
<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/1.gif") %> data-lightbox="set" data-title="Ise Ujbashi no zu (Image of Ujibashi, Ise)  伊勢宇治橋の図">
            <%= image_tag("prints/1.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/2.gif") %> data-lightbox="set" data-title="Ise Futami ura (Futami Bay, Ise)　伊勢二見浦">
            <%= image_tag("prints/2.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/3.gif") %> data-lightbox="set" data-title="Hyūga Takachiho mine (Takachiho Ridge, Hyūga)　日向高千穂峯">
            <%= image_tag("prints/3.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/4.gif") %> data-lightbox="set" data-title="Izumo taisha (Izumo Grand Shrine)　出雲大社">
            <%= image_tag("prints/4.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/5.gif") %> data-lightbox="set" data-title="Kirishima jingū (Kirishima Shrine)　霧島神宮">
            <%= image_tag("prints/5.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/6.gif") %> data-lightbox="set" data-title="Takachihō kyō Manai taki (Manai Falls, Takachiho Gorge) 高千穂峡真名井瀧">
            <%= image_tag("prints/6.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/7.gif") %> data-lightbox="set" data-title="Udo jingū (Udo Shrine) 鵜戸神宮">
            <%= image_tag("prints/7.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/8.gif") %> data-lightbox="set" data-title="Higo Aso jinja (Aso Shrine, Higo)　肥後阿蘇神社">
            <%= image_tag("prints/8.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/9.gif") %> data-lightbox="set" data-title="Hyūga Miyazaki jingū (Miyazaki Shrine, Hyūga)　日向宮崎神宮">
            <%= image_tag("prints/9.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/10.gif") %> data-lightbox="set" data-title="Yamato Niukawakami jingū (Niukawakami Shrine in Yamato)　大和丹生川上神社">
            <%= image_tag("prints/10.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/11.gif") %> data-lightbox="set" data-title="Kishū Kameyama-miya fukin (The Neighborhood of Kameyama Shrine, Kishū)　紀州亀山付近">
            <%= image_tag("prints/11.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/12.gif") %> data-lightbox="set" data-title="Kishū Nichizengū (Nichizen Shrine, Kishū)　紀州日前宮">
            <%= image_tag("prints/12.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

app/views/pages/_gallery2.html.erb
<!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/13.gif") %> data-lightbox="set" data-title="Yamato Kashihara jingū (Kashihara Shrine, Yamato) 大和橿原神宮">
                    <%= image_tag("prints/13.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/14.gif") %> data-lightbox="set" data-title="Atsuta jingū (Atsuta Shrine) 熱田神宮">
                    <%= image_tag("prints/14.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/15.gif") %> data-lightbox="set" data-title="Sesshū Sumiyoshi jingū (Sumiyoshi Shrine, Sesshū)　摂州住吉神社">
                    <%= image_tag("prints/15.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/16.gif") %> data-lightbox="set" data-title="Nara no yoru (Nara at Night)　奈良の夜">
                    <%= image_tag("prints/16.gif", :class => "img-responsive") %>
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/17.gif") %> data-lightbox="set" data-title="Yamato Hōryūji (Hōryūji Temple in Yamato) 大和法隆寺">
                    <%= image_tag("prints/17.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/18.gif") %> data-lightbox="set" data-title="Nara Kasuga jingū mantōrō zu (Image of Kasuga Shrine Ten Thousand Lanterns, Nara)　奈良春日神宮万燈籠の図">
                    <%= image_tag("prints/18.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/19.gif") %> data-lightbox="set" data-title="Usa jingū (Usa Shrine)　宇佐神宮">
                    <%= image_tag("prints/19.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/20.gif") %> data-lightbox="set" data-title="Kyoto Heian jingū (Heian Shrine, Kyoto)　京都平安神宮">
                    <%= image_tag("prints/20.gif", :class => "img-responsive") %>
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/21.gif") %> data-lightbox="set" data-title="Kishū Kōyasan (Mt. Kōya, Kishū) 紀州高野山">
                    <%= image_tag("prints/21.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/22.gif") %> data-lightbox="set" data-title="Chikushi Dazaifu Tenmangū (Dazaifu Tenmangū Shrine in Chikushi)　筑紫太宰府天満宮">
                    <%= image_tag("prints/22.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/23.gif") %> data-lightbox="set" data-title="Aki Miyajima (Miyajima, Aki) 安藝宮島">
                    <%= image_tag("prints/23.gif", :class => "img-responsive") %>
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href= <%= image_path("prints/24.gif") %> data-lightbox="set" data-title="Sōshū Tsurugaoka Hachimangū (Tsurugaoka Hachimangū Shrine, Sōshū) 相州鶴岡八幡宮">
                    <%= image_tag("prints/24.gif", :class => "img-responsive") %>
                </a>
            </div>
        </div>
        <!-- /.row -->

app/views/pages/_gallery3.html.erb
<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/25.gif") %> data-lightbox="set" data-title="Sōshū Kamakura daibutsu (Great Buddha of Kamakura, Sōshū) 相州鎌倉大仏">
            <%= image_tag("prints/25.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/26.gif") %> data-lightbox="set" data-title="Chikuzen Hakozaki Hachimangū (Hakozaki Hachiman Shrine, Chikuzen) 筑前箱崎八幡宮">
            <%= image_tag("prints/26.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/27.gif") %> data-lightbox="set" data-title="Kyoto Kinkakuji (Kinkakuji, Kyoto)　京都金閣寺">
            <%= image_tag("prints/27.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/28.gif") %> data-lightbox="set" data-title="Yamashiro Kasagiyama (Kasagiyama, Yamashiro)　山城笠置山">
            <%= image_tag("prints/28.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/29.gif") %> data-lightbox="set" data-title="Yamato Yoshinoyama (Yoshino Mountain, Yamato)　大和吉野山">
            <%= image_tag("prints/29.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/30.gif") %> data-lightbox="set" data-title="Inshū Nawa jingū (Nawa Shrine, Inshū)　因州名和神社">
            <%= image_tag("prints/30.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/31.gif") %> data-lightbox="set" data-title="Sōshū Kamakuragu (Kamakura Shrine, Sōshū)　相州鎌倉宮">
            <%= image_tag("prints/31.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/32.gif") %> data-lightbox="set" data-title="Yamato Shigisan (Mt. Shigi in Yamato) 大和信貴山">
            <%= image_tag("prints/32.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/33.gif") %> data-lightbox="set" data-title="Kawachi Kanshinji (Kanshin Temple, Kawachi)	河内歓心寺">
            <%= image_tag("prints/33.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/34.gif") %> data-lightbox="set" data-title="Hyōgo Minatogawa jingū (Minatogawa Shrine, Hyōgo)　兵庫湊川神社">
            <%= image_tag("prints/34.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/35.gif") %> data-lightbox="set" data-title="Sōshū Odawara jōshi (Remains of Odawara Castle, Sōshū)　相州小田原城趾">
            <%= image_tag("prints/35.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/36.gif") %> data-lightbox="set" data-title="Osaka-jo no zu (View of Osaka Castle)　大阪城の図">
            <%= image_tag("prints/36.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

app/views/pages/_gallery4.html.erb
<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/37.gif") %> data-lightbox="set" data-title="Kyoto Kiyomizudera (Kiyomizudera, Kyoto)　京都清水寺">
            <%= image_tag("prints/37.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/38.gif") %> data-lightbox="set" data-title="Nagoya jō (Nagoya Castle)　名古屋城">
            <%= image_tag("prints/38.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/39.gif") %> data-lightbox="set" data-title="Shimotsuke Nikkō Tōshōgū (Nikkō Tōshōgū Shrine, Shimotsuke)　下野日光東照宮">
            <%= image_tag("prints/39.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/40.gif") %> data-lightbox="set" data-title="Inshū Matsue jo (Matsue Castle, Inshū)　因州松江城">
            <%= image_tag("prints/40.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/41.gif") %> data-lightbox="set" data-title="Suō Kintaikyō (Kintaikyō, Suō)　周防錦帯橋">
            <%= image_tag("prints/41.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/42.gif") %> data-lightbox="set" data-title="Ōmi Katata Ukimidō (Floating Temple of Katata, Ōmi)　近江堅田浮御堂">
            <%= image_tag("prints/42.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/43.gif") %> data-lightbox="set" data-title="Banshū Akō Ōishi Yoshi kyūtaku (Former Residence of Ōishi Yoshio in Akō, Banshū)　播州赤穂大石良雄旧宅">
            <%= image_tag("prints/43.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/44.gif") %> data-lightbox="set" data-title="Kyōto gosho (Kyoto Imperial Palace)　京都御所">
            <%= image_tag("prints/44.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/45.gif") %> data-lightbox="set" data-title="Higo Kumamoto jō (Kumamoto Castle, Higo)　肥後鵜熊本城">
            <%= image_tag("prints/45.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/46.gif") %> data-lightbox="set" data-title="Kagoshima Shiroyama (Shiroyama, Kagoshima)　城山鹿児島">
            <%= image_tag("prints/46.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/47.gif") %> data-lightbox="set" data-title="Hiroshima Daihon’ei (Hiroshima Headquarters)　広島大本営">
            <%= image_tag("prints/47.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/48.gif") %> data-lightbox="set" data-title="Meiji jingū (Meiji Shrine)　明治神宮">
            <%= image_tag("prints/48.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

app/views/pages/_gallery5.html.erb
<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/49.gif") %> data-lightbox="set" data-title="Nijūbashi (Nijūbashi Bridge)　二重橋">
            <%= image_tag("prints/49.gif", :class => "img-responsive") %>
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href= <%= image_path("prints/50.gif") %> data-lightbox="set" data-title="Miyazaki hakkō ichiu no kichū (Foundation Pillar of the Entire World Under One Roof, Miyazaki)　宮崎八紘一宇の基柱">
            <%= image_tag("prints/50.gif", :class => "img-responsive") %>
        </a>
    </div>
</div>
<!-- /.row -->

app/views/pages/gallery.html.erb
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Tokuriki Tomikichirō 徳力富吉郎
                    <small>Scenes of Sacred and Historic Places</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <%= render "gallery1" %>
        <%= render "gallery2" %> 
        <%= render "gallery3" %>
        <%= render "gallery4" %>
        <%= render "gallery5" %>
    </div>
    <!-- /.container -->
    <%= javascript_include_tag "lightbox.js" %> 
</body>

app/views/pages/home.html.erb
<body class="home">
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <div class="inner cover">
          <h1 class="cover-heading"><strong> TOKURIKI 徳力</strong> </h1>
          <p>The work of Tokuriki Tomikichirō 徳力富吉郎 (1902-2000) is often described as an important bridge between the two great movements of Japanese art in the early twentieth century ー shin hanga (新版画) and sosaku hanga (創作版画).
            Like the classic shin hanga masters of the day, Tokuriki designed many woodcuts of landscapes and city views in the traditional manner, but also actively promoted sosaku hanga (creative prints) in Kyoto, which emphasized the exploration of more modern styles and trends.</p>
          <p>In appreciation of the sites featured in Tokuriki's 1941 series, <i>Scenes of Sacred and Historic Places</i>, we have mapped each print to its modern-day counterpart and are excited to present a new, interactive way of learning more about some of Japan's most beautiful and well-known locales. Please click the explore button to view the map, or the gallery button for more details regarding the print series.</p>
          <p class="lead">
            <%= link_to "GALLERY", gallery_path, :class => "btn btn-lg btn-default" %>
            <%= link_to "EXPLORE", explore_path, :class => "btn btn-lg btn-default" %>
          </p>
        </div>

        <div class="mastfoot">
          <div class="inner">
            <p> <small>This application was built for the exhibition "A Sense of Place: Modern Japanese Prints" curated by Professor Julie Nelson Davis, located at the University of Pennsylvania Arthur Ross Gallery from April 10th - June 21, 2015. For more information about the exhibit, please visit the following <a href="http://www.arthurrossgallery.org/events/event/a-sense-of-place-modern-japanese-prints/"> link</a>. Built by <a href="https://fling.seas.upenn.edu/~gracexu">Grace Xu</a>.</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>